### ISSUE TITLE
Fitbit Error E502

### ISSUE THREAD

**Issue by tmsilveira** [Rytiggy/Glance#122]
Hello! I just set up my Fitbit with Nightscout. On my watch, I keep getting the E502 error code. I set everything up correctly on the Glance watch face. What does that code mean?

**Comment by Rytiggy** [comment]
Hey, is your nightscout site working? would you mind sharing your Glance logs with me? 

To share your logs: 
Navigate to the bottom of Glance's settings and toggle advanced. then open up the logs text box and long press and select all and copy that text.

**Comment by tmsilveira** [comment]
I could copy it so here’s a pic. 

Thank you,
Terianne Silveira

**Comment by Rytiggy** [comment]
you have top open the logs text box before you try to copy it. once its opened long-press till you see select all, click select all, then click copy.

**Comment by tmsilveira** [comment]
I tried and it doesn’t give me that option. And yes Nightscout is working on my kindle fire. 

Thank you,
Terianne Silveira

**Comment by Rytiggy** [comment]
Could you share your nightscout link with me?

**Comment by Rytiggy** [comment]
Also, I did not receive a picture, could you screenshot each of the settings you have entered into Glance? and send them here.

**Comment by tmsilveira** [comment]
I fixed it. I just went into Nightscout and the sharing button wasn’t on. I’m good to go!!! Thank you so much for responses back to me!!!

Thank you,
Terianne Silveira

**Comment by Rytiggy** [comment]
Okay perfect!
