### ISSUE TITLE
User Agreement stays on the top even if you accept

### ISSUE THREAD

**Issue by whynot2018** [Rytiggy/Glance#125]
Hi
I trying to use Glance pre-release with my Fitbit Versa 2. I set up all settings and try to start. On my watch there is a User Agreement Glance must not be used to make medical decisions. I Agree.
I try to select to accept. it won't accept and the watch screen always stays like that.
Best regards.

**Comment by thomaas** [comment]
Hey @whynot2018! Did you agree in the settings as well? I know this issue but cannot reproduce within a debugging setting. In my case, a restart of the watchface (just open another app on your watch) helps because all settings then will be fetched by the companion app on the phone..

**Comment by whynot2018** [comment]
Yes it worked after I restart my watch and change some settings.But installation process took to long beside other watch faces.
