### ISSUE TITLE
pre release 1.1.0: companion diffMs calculation doesn't work on iPhone

### ISSUE THREAD

**Issue by rajid** [Rytiggy/Glance#13]
I mentioned this already and you seemed to agree it works, but I seem to still need to manually apply this change in order to have the pre-release 1.1.0 branch code work with my iPhone, so I thought I'd mention it here.  Just remove this if it's not needed.

If the diffMs calculation is done this way, it should work for both iPhone and Android:

        let date = new Date();
        let currentBgDate = new Date(data[0].date);
        let diffMs = (date.getTime() - currentBgDate); // milliseconds between now & today

**Comment by rajid** [comment]
Latest 1.1.2 seems to work with my iphone so I'll close this.

**Comment by Rytiggy** [comment]
Awesome let me know how it works :)
