### ISSUE TITLE
Always On watchface?

### ISSUE THREAD

**Issue by Arakon** [Rytiggy/Glance#150]
I got a Versa 3 today and had to return it for the simple reason that the glucose reading is only available when the watch is turned or the button is pressed. I read that there are watchfaces that have their own AoD view. Is there any chance that Glance would implement this as well, to basically show a darkened view that has the glucose reading and trend still visible?

**Comment by Rytiggy** [comment]
glance will continue to alert you and retrieve blood sugars when the screen is off. You must of not had background app refresh turned on in your phone settings for the Fitbit app. 

As for AOD there's currently no way for me to get approved to use it as Fitbit has it locked down, I want to add it as soon as Fitbit allows it.

**Comment by Arakon** [comment]
I'm aware of it still collecting data, my issue is that it's not possible to just briefly glance at the watch while working or in a meeting without having to fiddle around with the semi-responsive "sense" button or theatrically lifting my arm up and turning the wrist to make it trigger the view.

But thanks for letting me know about Fitbit having that locked down, maybe when the option becomes available, I may have another look at one.
Also. thank you for your work on this!

**Comment by Rytiggy** [comment]
No problem!
