### ISSUE TITLE
Feature suggestion:  move battery % inside of the battery symbol...

### ISSUE THREAD

**Issue by gitanO0** [Rytiggy/Glance#16]
... like this:  https://github.com/cmspooner/Kearsarge-Time-for-Fitbit-Ionic

Seems to be a very sleek and real estate efficient way to show the battery stuff especially if you ever look to add more stuff into the watch face at some later date.

**Comment by Rytiggy** [comment]
I like this! will add to my todo list! 🎉

**Comment by Rytiggy** [comment]
added in v1.2.0
