### ISSUE TITLE
Glance not showing any values when pulling from xDrip which is in turn pulling from BYO Dexcom app

### ISSUE THREAD

**Issue by 15characterlimi** [Rytiggy/Glance#162]
I run the [Build your own Dexcom app](https://docs.google.com/forms/d/e/1FAIpQLScD76G0Y-BlL4tZljaFkjlwuqhT83QlFM5v6ZEfO7gCU98iJQ/viewform) which broadcasts glucose readings to xDrip+. When setting Glance to pull from xDrip+'s webserver, it never shows any values. Upon debugging, the reason for this appears to be as follows:

 - Unless the query parameter `all_data` is present or the app is running in "follower" mode, xDrip+'s /sgv.json endpoint ([code](https://github.com/jamorham/xDrip-plus/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/webservices/WebServiceSgv.java#L121)) will only return values associated with the "current sensor" in xDrip+'s database.
 - On my phone, there are no sensor entries in xDrip+'s database and therefore the /sgv.json endpoint always returns an empty list of readings. Concretely, on my phone,
   - if I navigate to `http://127.0.0.1:17580/sgv.json?count=47`, I get the response `[]` (JSON for an empty array)
   - if I navigate to `http://127.0.0.1:17580/sgv.json?count=47&all_data=true` then I get the expected readings (the value "true" is arbitrary).
   - when I change xDrip+ to always ignore the sensor (hardcode `ignore_sensor=true`), then Glance successfully shows the readings from xDrip+
 - I don't know why xDrip+ on my phone doesn't associate readings with any sensors, but I suspect it is because I don't let xDrip+ talk to my sensor directly I don't trust it to be the main source of truth and storage for my readings).
 - I don't know what it takes for xDrip+ to consider itself in "follower" mode, but I suspect it has to do with the feature of running xDrip+ on multiple phones on which one is the master that talks to the sensor, and the other phones following that master (I'm not running xDrip+ in this mode).

Arguably, it is a bug that xDrip+ isn't returning the values when the values are received from the BYO Dexcom app; it should return them, either by associating the values with an inferred or fake sensor, or by also considering itself in follower mode in that case, or by just always returning all data (there's probably a reason why xDrip+ doesn't want to always return all values, but I can't think of one).

I will shortly upload a pull request that works around this issue by passing the query parameter `all_data=true` when pulling from xDrip. My hope is that other Glance users who run xDrip+ in the same configuration as I will benefit.

**Comment by 15characterlimi** [comment]
I expect https://github.com/Rytiggy/Glance/pull/163 to fix this issue.

**Comment by Rytiggy** [comment]
Merged! thank you go in my next release!
