### ISSUE TITLE
Enhacement request:  glucose alerts, disabling and custom snoozing time

### ISSUE THREAD

**Issue by gitanO0** [Rytiggy/Glance#18]
I love the new high/low alerting and would like to request a couple things to that functionality:

- Allow user to disable and re-enable somehow.  Use case:  I just put on new sensor, for the first day I get a lot of high and low readings that aren't accurate... Today for example...  On my watch, I have to hit the snooze and/or mute button (not sure what the difference is) **a lot**.  As well, I may be in a long meeting and I know I'm running high but I don't want buzzes and vibrations bugging me all day until I can deal with it. 

- Possibly the same request as above... but have a way to set a custom snooze time length.  For example, if I could choose 3 hours or even 5 hours or some such, that would alleviate issues like in bullet one.  

- Or perhaps even more fine grained settings for this such as "only alert on lows".

- Or perhaps make it so the "mute" button really does mute the alerts until you click a little icon or something to turn alerts back on.  Currently, and I haven't figured out snooze vs mute, but it seems that when I press either, within just a short amount of time again I'm getting alerted.  When I'm over 200 and it's taking time to come back down, that's a lot of buzzing going on.

Anyway, just ideas here... but the gist is, sometimes my watch is buzzing at me because of known highs and I'd like to be able to just turn that off with some sort of level of control/customizablity.

**Comment by jseaber** [comment]
Agreed. The Mute/Snooze feature resets with every new glucose reading. We need an option field to define mute and snooze duration.

I'd prefer the option to Enable or Disable watch alerts and rely exclusively on xDrip+ alerts from my phone, where alerts can be customized in greater detail. Watch alerts may be useful at times, but two devices buzzing is generally overkill.

**Comment by jdslabs** [comment]
@gitanO0 - Sorry, my wording was unclear. I agree with your suggestions. Alert data is not contained in `sgv.json`.

Rather, I want alerts to occur exclusively on my phone. I do not want to manage redundant alerts on my watch most of the time. Watch alerts may be desirable under different situations, so from a development standpoint, a master ON/OFF option for alerts should be helpful. Further option refinement as you've suggested would be useful when alerts are enabled.

**Comment by jseaber** [comment]
@gitanO0 - Sorry, my wording was unclear. I agree with your suggestions. Alert data is not contained in sgv.json.

Rather, I want alerts to occur exclusively on my phone. I do not want to manage redundant alerts on my watch most of the time. Watch alerts may be desirable under different situations, so from a development standpoint, a master ON/OFF option for alerts should be helpful. Further option refinement as you've suggested would be useful when alerts are enabled.

**Comment by Rytiggy** [comment]
This is all amazing thanks for the suggestions! I could add a setting in the settings that allows you to disable or enable of alerts based on your choice.

**Comment by Rytiggy** [comment]
Hey guys I've just released [1.1.4](https://github.com/Rytiggy/Glance/releases/tag/1.1.4) which has the ability to disable alerts and select your units type, Let me know what you think!💯

**Comment by nightscoutdb** [comment]
Firstly, huge thank you for making the watch face!

To add on to what's been said above, would it be possible to customize how long snooze/mute lasts for? At the moment both mute/snooze only seem to disable alerts for a few minutes at most.

**Comment by pmcdougal** [comment]
.
