### ISSUE TITLE
Issue:  Weather data doesn't update properly

### ISSUE THREAD

**Issue by gitanO0** [Rytiggy/Glance#19]
I've noticed that the weather data, for some reason, doesn't update as frequently as the actual json feed suggests it should.  If I open my openweathermap json api feed, in a browser URL I notice that it is often updated where the watch data is not.  What's odd is that given the same update cycle, the bg data is up to date.   I looked through the code and can't figure this out.

There are many times where I visit the same exact openweathermap url in my browser as what is being used in Glance and the json string returned in the browser is up to date  and the data that is displayed in the Glance clockface is not updated... and will continue to lag for 20 or more minutes.   What is odd is that the data from xdrip+ seems to always be as up to date was what I see on my phone xdrip app.  

Something odd is going on that is not allowing Glance to update the weather data on a timely basis.  I've looked at the code and both the weather feed and the xdrip feed seem to use the same type of code base so I have no idea why the weather data seems not to want to update properly.  

From a minor amount of monitoring, it seems that the weather feed does ok for a couple of updates then it stops updating in a timely fashion, then after a delay of 30 minutes or so, starts back up again. rinse... repeat.

I guess the way to verify this is to bring up a openweathermap json feed in a browser and monitor its results vs what is showing in the Glance clockface... at least a couple times an hour, the clockface lags well behind what shows in the json results in the browser.  

Any ideas?

**Comment by gitanO0** [comment]
I think I have the answer:  https://openweathermap.org/price... free accounts don't only get data updated in a frequent manner... the price page says "< 2hours"... that kinda stinks.  When you actually look at there data plans, the price is outrageous.  Wonder what other free weather providers are out there that would work better?  Yahoo?

**Comment by Rytiggy** [comment]
I'll look in to other options for weather data, this is a good suggestion! :)

**Comment by gitanO0** [comment]
I just got a weatherunderground api key for free and this looks way more comprehensive, updates every few minutes, and i can pick weather stations that are very close to my house.
