### ISSUE TITLE
steps and heartrate data back to xdrip

### ISSUE THREAD

**Issue by gitanO0** [Rytiggy/Glance#21]
I've been looking into xdrip's api to get steps and heart rate back to xdrip but am falling short in my technical knowledge... I know we can append current heart and steps data to a local web service url using the "?steps=xxx&heart=yyy" syntax but I'm not sure how to actually code it on the fitbit side... somehow that data has to be passed back out to the companion and then that url has to be triggered... once that happens, xdrip will show the heart and steps data.  Just not sure how to do all that.  Do you have any experience in this?

**Comment by Rytiggy** [comment]
I haven't done it yet, but that being said I would probably have an event that would trigger the companion to send the data to xdrip

**Comment by gitanO0** [comment]
It's actually pretty straight forward... in the main app index code... 
_function fetchCompaionData(cmd) {
  setStatusImage('refresh.png')
  if (messaging.peerSocket.readyState === messaging.peerSocket.OPEN) {
    // Send a command to the companion
    messaging.peerSocket.send({
      command: cmd**,
      heart: heartRate.heartRate,
      steps: today.local.steps**
    });
  } 
}_

Then in the companion index code...
_messaging.peerSocket.onmessage = function(evt) {
  if (evt.data) {
    formatReturnData();
    **SendSensorDataToPhone(evt.data);**
  }
}_

and 

_**function SendSensorDataToPhone(data) {
  let sendSensorsURL = "http://127.0.0.1:17580/sgv.json?heart=" + data.heart + "&steps=" + data.steps;
  return fetch(sendSensorsURL)
  .then(function (response) {
     return response.json()
      .then(function(data) {
      });
  })
  .catch(function (err) {
    console.log("Error sending heart and steps data" + err);
  });
}**_

**Comment by Bard09** [comment]
Is this functionality 'baked in' to Glance now?  If so, how do we configure Xdrip+ 's motion settings to take advantage of it?
