### ISSUE TITLE
No data on my versa watch

### ISSUE THREAD

**Issue by Lien64** [Rytiggy/Glance#22]
I installed my versa-fitbit according to Miguel's instructions from the spike app. I can not see the data on my watch.
I reset the watch to the factory setting and reinstalled everything. Still no data ???
I have installed the following API: http://127.0.0.1:1979
Can you help me to solve this problem?

Sorry for my english; i’m from the netherlands en my english is not very good ☺️☺️; google translate works for me......

**Comment by Rytiggy** [comment]
@Lien64  are you still having this issue with the latest version? 

Your API url should look like this http://127.0.0.1:1979/sgv.json

let me know if this helps

**Comment by Thasgolas** [comment]
I am still having this issue (that updates do not occur)

**Comment by Rytiggy** [comment]
@thasgolas did you update to the latest version? 1.2.0

**Comment by Thasgolas** [comment]
Yes.

**Comment by Rytiggy** [comment]
@Thasgolas  What does your API endpoint look like?  do you have all your settings filled out?
there were some new settings added in 1.2.0 that need to be filled out in order for the watch to update. Could you send me a picture of your settings on github?

**Comment by Thasgolas** [comment]
Will try and send a picture.  The endpoint os http://127.0.0.1:17580/sgv.json <http://127.0.0.1:17580/sgv.json>

**Comment by Rytiggy** [comment]
If you go to that API endpoint (http://127.0.0.1:17580/sgv.json) on your phone's browser can you see data?

Also I did not recieve any screenshots

**Comment by grlcastro** [comment]
Hi, i´m new here, and i´m having issue to see the info on Versa, from nightscout. What is the sgv.sjon ? Should i make any change on heroku??
tks
