### ISSUE TITLE
Setting to not alert when no heart rate detected. 

### ISSUE THREAD

**Issue by cramis1** [Rytiggy/Glance#24]
Sometimes I don't wear my watch overnight while I sleep. However, when an alert happens at night, the watch will vibrate all night and be empty of battery by the morning. Perhaps it would be useful to have an optional setting that if there is no heart rate detected within, for example 30 minutes, to turn off alerts because it indicates the watch is not being worn.

**Comment by Rytiggy** [comment]
I like this good suggestion
