### ISSUE TITLE
Request: send HR/step data to XDrip (if possible)

### ISSUE THREAD

**Issue by Bard09** [Rytiggy/Glance#27]
It looks like from this closed Issue (https://github.com/Rytiggy/Glance/issues/21) that sending HR/step data from the Ionic/Versa might be possible-- but I'm not seeing any step/HR data in my Xdrip+ from my Versa.  I am using a Pixel 2 phone.

A) is this functionality possible?
B) if so, is this currently implemented?  (not sure from the closed Issue)
C) does Xdrip+ need to change to support this?

Thanks!

**Comment by gitanO0** [comment]
I added those code snippets as suggestions for issue 21.  I do have a modified version of Glance on my Versa with heart/step data going to my phone/xdrip+. 
A)  It's definitely possible.  If Ryan implements code similar to what is in that issue 21 suggested, Glance should send that data to xdrip+ no problem.  
B) I'm not seeing that this change was made in any of the Glance code so not sure why it was closed.
C)  In xdrip+, once it's implemented in Glance, you need to turn on the smartwatch settings for "health data... heart and steps".

**Comment by Bard09** [comment]
Thanks @gitanO0.  I'm glad to hear it's possible!  We'll see what Ryan has to say about including it as a feature :)

**Comment by Bard09** [comment]
@gitanO0 Haven't heard from Ryan on this... I'm assuming he's busy with other support priorities.  If you have a chance, maybe you could submit your HR/step data mod as a pull request here?  Maybe that'll get this moving forward.  Fingers crossed 👍

**Comment by Rytiggy** [comment]
Completely missed this thread, I can probably get this feature added by the next release ( I want to release at the end of the month ).  If one of you wanted to do a PR for it I would be so thankful:) haha but I can definitely impliment something when I find some time to do so!

**Comment by Bard09** [comment]
Thank you for the reply!  Looking forward to trying it out :)
