### ISSUE TITLE
Inquiry (more than issue) about Versa 4

### ISSUE THREAD

**Issue by bentonmize** [Rytiggy/Glance#304]
So I'm just curious if/how you're developing for the newer devices, like Sense 2 and Versa 4 since it seems like there is no longer going to be SDK support.  Usually if I have any issues I just open it up and modify, but I picked up a Versa 4 for a good deal and then later found that there was no real dev support.  I've seen stuff on some kinda sideloading etc, but I wondered what you were thinking future wise.  I'm having some connectivity issues with the Glance face whenever I walk out of range of my phone and then back, it just doesn't seem to reconnect.  This was not an issue before the update to the Versa 4 put out a few weeks ago.

Thanks!

**Comment by bendoerr** [comment]
Someone also posed about similar Versa 4 issues on Discord (https://discord.gg/zwvkJkbnY4). I would love to know more if you find out anything. Unfortunately, Glance is mostly in maintenance mode at this point. @Rytiggy doesn't have a ton of time right now. From what I know Fitbit is being slowly retired however. I'll talk with him to see if we can get a SDK update soon.

**Comment by bentonmize** [comment]
Yeah my understanding was this might be a tactical move to push people to Pixel Watch but lotta back and forth talk from Google.  Thanks for responding!

**Comment by bendoerr** [comment]
No prob. If you are able to find anything specific like a thread talking about how to resolve the issue on the software side let us know and we can try it out.
