### ISSUE TITLE
Settings update

### ISSUE THREAD

**Issue by beccapollard** [Rytiggy/Glance#31]
My background colour won't change despite syncing and switching from purple to green. The graph for blood sugars is also not switching to my high and low settings

**Comment by Rytiggy** [comment]
@beccapollard Hey! What is your setup? Do you have your sugars in the cloud (accessible through the cloud)? 

Could you send a picture of your settings for Glance?

**Comment by beccapollard** [comment]
I got it all figured out, thank you!

**Comment by rhinot1d** [comment]
I have a the same issue. No color change and no glucose info on the watch.

**Comment by Rytiggy** [comment]
Could you send me a pic of your Glance settings?
