### ISSUE TITLE
Not in Gallery anymore: download links broken, no way to install

### ISSUE THREAD

**Issue by arty-name** [Rytiggy/Glance#318]
Both download links on the [home page](https://glancewatchface.com/) (for stable release and the beta version) have stopped working for me. They lead to a 404 page in the Fitbit Clocks gallery. 

Looking at the list of Clocks in the gallery, I don’t see Glance anymore. 

Is it still possible to install Glance from scratch? I can’t find mentions of this issue in the GitHub.

**Comment by Rytiggy** [comment]
I'm guessing you are outside the US? You probably need to use a VPN and set the location in the US to download Glance.

**Comment by arty-name** [comment]
Thank you for the swift response!

Indeed I am from EU, but I successfully installed Glance a few times in previous years. 

I assume this is a recent issue… Is it mentioned somewhere for my unsuspecting brethren?

**Comment by Rytiggy** [comment]
Google has this support post about it: https://support.google.com/fitbit/answer/14237121?hl=en

**Comment by arty-name** [comment]
Quite recent. Thank you for the link! 

I guess I’ll close this, unless you want to also add this link somewhere on the website.
