### ISSUE TITLE
Larger BG curve display on a sidescreen

### ISSUE THREAD

**Issue by dv1** [Rytiggy/Glance#32]
This has no priority, but would be a nice enhancement I think.
Currently, if I try to swipe the watchface to the right, I see that there's nothing to the left of the watchface, so I can't swipe. I think this unused space would be perfect for a full-screen display of the BG curve. This way, the main watchface screen gives me an overview over all values, and if I want to see the BG curve in greater detail, I swipe the watchface to the right, and see a fullscreen BG curve. What do you think?

**Comment by Rytiggy** [comment]
I am thinking about a second screen that would hold a larger view of the graph as well as information like the raw IOB and COB values.
