### ISSUE TITLE
iOS and Versa

### ISSUE THREAD

**Issue by rhinot1d** [Rytiggy/Glance#33]
Ok so im a total noob here but i cannot seem to get this to work on my Versa. i have followed all the steps to set up my azure site and everything is working. i can use my url to work with the simple cgm watch face but cannot get the glucose to display on Flash CGM or glance. 

any advice would be appreciated.

**Comment by Rytiggy** [comment]
Hey @rhinot1d, could you send me a pic of your settings ? 

Glance updates every 5 minutes from whenever it received the BG, if you want to sync It better you can try refreshing the watch face, to do this swipe up from the bottom of the screen opening today then go back to Glance by hitting the back button. This will foce Glance to reset and pull the bgs again.

**Comment by rhinot1d** [comment]
@Rytiggy. Thanks for the response! I reset my Versa last night to factory settings and reloaded it and everything seems to be working as it should. Thank you so much for setting up this system! It’s going to be a huge help.

**Comment by Rytiggy** [comment]
Glad to hear that :)

**Comment by rhinot1d** [comment]
I have glance set up through the Spike app. the only issue I've had so far is the Dexcom G5 app seems to not want to keep its connection. The spike app is doing fine and transmits the info as it should. Hav you had anyone experience this issue?

**Comment by Rytiggy** [comment]
Yeah there seems to be quite a few people who have experienced some sort of
signal dropoff, I have yet to pin point the cause of it, but from what I
have gathered it seems like the Fitbit app will stop syncing with the
Fitbit watchface causing Glance not to be able to pull the latest bg. One
thing that seems to help is to make sure all day sync is turned on as well
as always connected and keep widgets alive in fitbits settings.

**Comment by rhinot1d** [comment]
Looking at my setup, Fitbit app is working and synced, Spike app is reading my Dexcom G5 and sending data to the watch face, Glance is pulling the BG as it should be. the only odd app out is the Dexcom G5 app which states "signal loss". 

The Spike app may be the culprit as it connects to the Dexcom G5 transmitter as well as the Dexcom G5 app. Maybe there is an issue with both the Dexcom G5 app and the Spike app connectiing simultainiously? If thats the case, Should i contact the folks at SpikeApp?

Just to be sure i mentioned it this is all on an iPhone 8+, Fitbit Versa (updated firmware)
Using the Dexcom G5 system and G5 App in conjuction with the Spike app.

Ill be upgrading to the Dexcom G6 but not until next week.

**Comment by rhinot1d** [comment]
Here’s some pics of the for reference 
![Image](https://i.imgur.com/3e5eI4W.jpg)
![Image](https://i.imgur.com/4VI1OCg.jpg)
![Image](https://i.imgur.com/2AkLQYo.jpg
![Image](https://i.imgur.com/6O7Kx17.jpg)

**Comment by Rytiggy** [comment]
I would reach out to Miguel Kennedy he is the creator of Spike.

I'm not sure if you are apart of the spike app facebook group but I would
highly recommend joining, they are super helpful and if the problem lies
with spike then I'm sure they will be able to help you out!
https://www.facebook.com/groups/spikeapp/

All your tech should be compatible. So I don't think its the
technology that's causing it to drop off just the software or a setting
that is doing it.

**Comment by rhinot1d** [comment]
I joined the group. As of right now everything is working between the app and Fitbit flawlessly.

I wish I had the knowledge to create my own watch face just to do it lol but I also wanted to say thanks again and you’ve done an outstanding job!

**Comment by Rytiggy** [comment]
I really appreciate that :) let me know if anything happens or if you need
any help!

**Comment by csmith144** [comment]
I'm experiencing similar problems, i can't change colors, can't see the updated glucose reading in the top right corner, and it doesn't auto update. What did you do to fix these problems? just a simple factory reset?

**Comment by Rytiggy** [comment]
Hey, @csmith144 It seems like that's what worked for @rhinot1d, Please let me know if it was successful for you. :)

**Comment by rhinot1d** [comment]
@csmith114 yes I just unpaired my Versa from my phone and did a factory reset on the Versa. Once I got it paired with my phone after the reset everything worked like normal.
