### ISSUE TITLE
Glance on Versa

### ISSUE THREAD

**Issue by laurakinney3149** [Rytiggy/Glance#34]
Hi! I'm struggling!   I've been able to get my nightscout information to show on other cgm watch faces.  I am using my Heroku Web address as the API. Is are correct?

**Comment by Rytiggy** [comment]
What is the Heroku Web address you are using?

**Comment by laurakinney3149** [comment]
http://lkdex.herokuapp.com

**Comment by Rytiggy** [comment]
Oh okay so the heroku web address (API end point) needs to have this on the end of it 
`/api/v1/entries/sgv.json`

So your final API endpoint should look like this 
http://lkdex.herokuapp.com/api/v1/entries/sgv.json

**Comment by laurakinney3149** [comment]
I will give that a try!

**Comment by laurakinney3149** [comment]
Hmmm still nothing.

**Comment by optleinoX** [comment]
Hi. I think im having the same issue on ionic/s7. Api url is ok, i get data from it. Seems like the watch/glance is not getting the settings from the phone app - units and background colors do not change.

Ive done factory reset once, did not solve it. Any tips what to try next, really looking forward getting this up and running.

**Comment by optleinoX** [comment]
To add on that, i still get notifications from the phone and steps etc find their way to my phone, so connection seems to be ok.

**Comment by louismorin** [comment]
I'm experiencing the same problem where my watchface will not update with new settings. Neither the blood sugar data or the other setting changes will populate even after a hard reset of my versa

**Comment by nicolasdexcom** [comment]
Im also have problems with my versa not updating/syncing. It keeps losing the connection.
