### ISSUE TITLE
how to use xdrip

### ISSUE THREAD

**Issue by verdadom** [Rytiggy/Glance#39]
Dear Ryan,
I am typ 1 diabetic and using medtronic 640g and CGM censor
I have questin for you I want tobuy fitbit versa, is this watch can be used with my CGM and insilun pump? What should I do to see my glocose levels on the watch should I buy glance? ıs the glance prgram used only at the watch and xtrip is beeing used on the phone only or are they combined programes?
Thank you very much
Best regards,

**Comment by verdadom** [comment]
Dear Ryan,
Is this app can be used at Turkey?

**Comment by Rytiggy** [comment]
Hey! @verdadom, what phone do you have Android or iphone?

If you're using Android you can follow this guide to get your blood sugars from your 640g to Nightscout. 

https://github.com/pazaan/600SeriesAndroidUploader/wiki/Android-Uploader-Installation

If you need help setting up your nightscout site you can follow this guide 

http://www.nightscout.info/wiki/welcome/set-up-nightscout-using-heroku

The app should be able to be used in Turkey, to check can you see the red select button in the Fitbit app store for Glance.

 https://gam.fitbit.com/gallery/clock/7b5d9822-7e8e-41f9-a2a7-e823548c001c

Let me know if you have any questions!

**Comment by verdadom** [comment]
Hi Ryan,

I am using android phone.


The link does not open.. https://gam.fitbit.com/gallery/clock/7b5d9822-7e8e-41f9-a2a7-e823548c001c
[cid:image001.png@01D4834E.A7EB4B10]
What is the Galance?

https://github.com/Rytiggy/Glance/blob/master/README.md

**Comment by Rytiggy** [comment]
You'll need to have the Fitbit app installed on your phone. And click this link on your phone not on your computer

https://gam.fitbit.com/gallery/clock/7b5d9822-7e8e-41f9-a2a7-e823548c001c

Glance is this repository. It is my Fitbit watch faces that helps visualize blood sugars on your Fitbit device.

**Comment by verdadom** [comment]
Hi Ryan,
How long does this process take?
I've been waiting since 09:00.
Is there something wrong?

[cid:image001.png@01D48666.A31C8B10]

**Comment by Rytiggy** [comment]
@verdadom what step are you on?

**Comment by verdadom** [comment]
Hi Ryan,

İs the Heroku create new app .

**Comment by verdadom** [comment]
[cid:image001.png@01D48669.D7B52CD0]



Sensitivity: Public
From: Verda Albayrak
Sent: Tuesday, November 27, 2018 3:56 PM
To: Rytiggy/Glance <reply@reply.github.com>; Rytiggy/Glance <Glance@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Rytiggy/Glance] how to use xdrip (#39)

Hi Ryan,

İs the Heroku create new app .

**Comment by Rytiggy** [comment]
Setting up a heroku site csn very from person to person, could you send me a pic of the step you're on

**Comment by verdadom** [comment]
Ryan,

This nightschout URL : https://obscure-hollows-17239.herokuapp.com  ?
[cid:image001.png@01D48672.A97D1E50]

**Comment by verdadom** [comment]
[cid:image001.jpg@01D48673.01991E40]



Sensitivity: Public
From: Verda Albayrak
Sent: Tuesday, November 27, 2018 5:00 PM
To: 'Rytiggy/Glance' <reply@reply.github.com>; Rytiggy/Glance <Glance@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Rytiggy/Glance] how to use xdrip (#39)

Ryan,

This nightschout URL : https://obscure-hollows-17239.herokuapp.com  ?
[cid:image001.png@01D48672.A97D1E50]

**Comment by Rytiggy** [comment]
Youll need to set up your profile you can find it here https://obscure-hollows-17239.herokuapp.com/profile

The profile is used for all your basal, Insulin sensitivity factor (ISF), Carb ration, and bg targets. fill out this page then click save at the bottom. Youll need to enter your API secrete on that page when you click save.

**Comment by verdadom** [comment]
Hi Ryan,

Thank you for your Support. Could you please help my other questions too?

As you have mentioned, I have added the values in my profile. Unlike in the website, I can add values for between 00:00 - 03:00 in my pump device. In the website ı can only add values of Insulin to carb ratio and Basal rates for 00:00

[cid:image002.jpg@01D48677.D57DF920]

Could you please inform me about how I can sync the values with my fitbit watch?
Do I have to connect contour next USB device to my phone, to see the continuous data on Nightscout screen?

**Comment by Rytiggy** [comment]
Yep that's correct for your site profile info. and also correct for the contour next USB device. It has to be connected to your phone in order to be able to get the data from your CGM,

**Comment by verdadom** [comment]
Hi Ryan,

Can you please answer the following questions?

Could you please inform me about how I can sync the values with my fitbit watch?
As you have mentioned, I have added the values in my profile. Unlike in the website, I can add values for between 00:00 - 03:00 in my pump device. In the website ı can only add values of Insulin to carb ratio and Basal rates for 00:00

[cid:image002.jpg@01D48677.D57DF920]

**Comment by Rytiggy** [comment]
To sync your bgs on nightscout with Glance enter your nightscout site name
in to Glance's settings under data source.

More info can be found here
https://github.com/Rytiggy/Glance/wiki/How-to-set-up-Glance#2-settings

**Comment by verdadom** [comment]
Ryan,

I synchronized with my fitbit clock😊

Where does this value come from(+3mg/dl)

want to display the value of active insulin.
[cid:image001.png@01D48740.7C89F660]

**Comment by Rytiggy** [comment]
That looks to be the delta it's the change from the last BG to the current
BG

**Comment by verdadom** [comment]
Hi Ryan,

How can I close the BG?
How do I display active insulin on the fitbit?

**Comment by verdadom** [comment]
Hi Ryan,

I can't see my active insulin value on my Fitbit watch? What could be the reason?

[cid:image001.png@01D48893.387886E0]

**Comment by Rytiggy** [comment]
What do you have your data source set as, you'll need to use nightscout as your data source if you want to see active insulin (IOB)

**Comment by verdadom** [comment]
Hi Ryan,

Can you please share the screehoot .

**Comment by Rytiggy** [comment]
In Glance's settings what do you have your data source set as?

**Comment by verdadom** [comment]
[Resim]



[Resim]


[Resim]





Android için Outlook<https://aka.ms/ghei36> uygulamasını edinin

________________________________
