### ISSUE TITLE
Feature request: Alarm/Vibration on values lower than treshold?

### ISSUE THREAD

**Issue by zshh** [Rytiggy/Glance#4]
Hi,

Would it be possible to have some kind of "notification" when BG value is lower than the "low treshold" value in the settings?
-Audible (using ionic's build in alarm somehow)
or even better
-Vibration in the watch itself (continuous one until you "mute/acknowledge" it)

Hope others would find this FR usable, so that it is worth while for you to perhaps implement it :)

Thanks

**Comment by Rytiggy** [comment]
Hey! This is a feature I definitely want to implement, I've made a ticket for it [seen here](https://github.com/Rytiggy/Glance/projects/1#card-8979940).  We can aim for adding it in the next release!

**Comment by Rytiggy** [comment]
added with 
https://github.com/Rytiggy/Glance/tree/release/1.1.3
