### ISSUE TITLE
Spike delta issue

### ISSUE THREAD

**Issue by andrewcarrick** [Rytiggy/Glance#40]
The latest version of spike (3.5.0) has changed the api to make it compatible with some older pebble watches (I think this is the cause) but this is making the delta show in mg/dl instead of mmol (I think) but it only happened after the update.

**Comment by Rytiggy** [comment]
Oh thank you for this I'll look in to it and fix it in the next update!!

**Comment by Rytiggy** [comment]
@andrewcarrick  Can you confirm that switching the Units type in Glances setting still effects the Delta?

**Comment by andrewcarrick** [comment]
Just changed the units and the delta is correct in mg/dl but the actual value is shown in mmol instead of mg/dl (values on the graph seem to change appropriately). I have got some photos but not sure I can attach here. Also if you need I can copy the Json from spike if you let me know which endpoint you are getting the data from.

**Comment by Rytiggy** [comment]
You can drag and drop the image in the GitHub comment box.

and please could you send the updated json?

**Comment by andrewcarrick** [comment]
Images of both units attached. 
The json from api/v1/sgv.json is
`[{"filtered":200353,"noise":1,"rssi":100,"device":"MIAOMIAO","type":"sgv","sysTime":"2019-01-02T19:38:31.000+0000","_id":"1546457911208333e138f4ea","sgv":178,"direction":"Flat","dateString":"2019-01-02T19:38:31.000+0000","unfiltered":200353,"date":1546457911161}]’
![24b7cdd8-1e0d-4eff-9a30-2fe023d79d51](https://user-images.githubusercontent.com/40068279/50608995-41194780-0ec6-11e9-8883-872cce4f5b07.jpeg)
![3169f7f2-b364-4d55-a4f8-213ed0a0356f](https://user-images.githubusercontent.com/40068279/50608996-41194780-0ec6-11e9-89eb-eb81559b928b.jpeg)

**Comment by Rytiggy** [comment]
This has been fixed in the pre-release and the update will come soon :)
