### ISSUE TITLE
Work on Dexcom trend arrow

### ISSUE THREAD

**Issue by Rytiggy** [Rytiggy/Glance#49]
@cutepooh Reports that the trend arrow can be off for her as well

**Comment by lcuozzo** [comment]
Trend arrow on Glance does not match arrow on Dexcom right away after a rapid rise or fall it takes about 15-20 minutes to catch up to match the right direction.

**Comment by StormeHawke** [comment]
Trend arrow for me is also off.  Right now I'm at 155, has gone *down* by 1mg/dl since last reading, but the arrow is showing the diagonal up arrow.

As a thought, maybe you could avoid re-inventing the wheel by cribbing the algorithm for the trend arrow from xdrip/xdrip+?

**Comment by StormeHawke** [comment]
now down to 153, still showing the diagonal up arrow

**Comment by StormeHawke** [comment]
And now it set itself at 154 and went to the right/stable arrow

**Comment by supermomof2girls** [comment]
I notice that my arrows dont always match when My BG is rising or dropping
