### ISSUE TITLE
Fix E404 showing up when you should be getting stale data.

### ISSUE THREAD

**Issue by Rytiggy** [Rytiggy/Glance#50]
Some users have reported getting e404 when the users settings are correct. 

the error that should be reported is LOS

@cutepooh report:
#### Dexcom Route
* I notice watch is not gotten a current reading
* resync in Fitbit app (versa)
* select Dexcom app
* BT off 20sec/on
* resync all and refresh Dexcom app
-> closed everything -> reopened, didnt fix. restarted phone, repeat all
* Fixed it by changing settings to NS, refreshing watch screen via picking weather /etc
*then switching back to the Dexcom app.

((This has been a regular issue off and on all day. It could be an app thing, but something I noticed. The steps and so on in the Fitbit app did sync just not the glucose values.))

**Comment by PedanticAvenger** [comment]
I had it at least once where there wasn't even any stale data.  But most of them I can agree were stale data situations.

**Comment by PedanticAvenger** [comment]
Ok, encountered this again, uploading logs to you.
Displayed E404, all history became a flat line, 
hit reload on watch face, no change.
forced a re-synd from fitbit app, 10 seconds later the watch face updated.
