### ISSUE TITLE
Feature request: Change SGV data point colours based on high/low thresholds

### ISSUE THREAD

**Issue by bmammon** [Rytiggy/Glance#7]
It would be great if the current BG number changed colour as well!

**Comment by Rytiggy** [comment]
I like this, I've added it to my todo list! great suggestion  😄

**Comment by zshh** [comment]
Cheers, same goes for the graph axis, you fixed it in earlier version to scale the numbers if mgdl or mmol, right now its stuck on the mgdl scale only tho ;)

Thanks for all the great work Ryan!

**Comment by Rytiggy** [comment]
Fixed with https://github.com/Rytiggy/Glance/tree/release/1.1.3
