### ISSUE TITLE
Custom endpoint not working

### ISSUE THREAD

**Issue by jaylagorio** [Rytiggy/Glance#77]
This is largely a continuation of #5 but with several changes. The end result is that on Nightscout, not hosted on Heroku or Azure, I still can't get this working on my iPhone (a change from #5) and my fully updated Versa without using Spike. This is important to me since Apple has made it so Spike isn't a reliable option anymore.

Reading through the code (https://github.com/Rytiggy/Glance/blob/f25773dbe4a6eb01b0be37c12e43248047b13333/modules/companion/settings.js#L34) it looks like I should need to use this as an endpoint:

http://nightscout.lagor.io/api/v2/properties

This returns the expected JSON in a browser on the desktop and on the iPhone. However, Glance shows E404 on the screen. What else can I try?

**Comment by Rytiggy** [comment]
Try using the custom data source option and entering this instead `http://nightscout.lagor.io/pebble`

**Comment by jaylagorio** [comment]
I tried this:

1) Update the URL
2) Force close the Fitbit app
3) Reopen and hit the Sync button
4) Reset/reload the watch face, tap the time to update

Unfortunately it still says E404.

**Comment by Rytiggy** [comment]
it looks like it's because your Nightscout site doesn't support HTTPS:
` Settings: Blocked insecure request to URL: http://nightscout.lagor.io/pebble?count=47`

Do you know if you can fix that?

**Comment by jaylagorio** [comment]
That's interesting - and possibly, but not easily. Can a setting, off be default so you have to really know you want it, be added to allow HTTP?

**Comment by Rytiggy** [comment]
Who are you using for your host?

**Comment by jaylagorio** [comment]
It's privately hosted: https://github.com/jaylagorio/Nightscout-on-Windows-Server

**Comment by Rytiggy** [comment]
I will look into the possibility of it being able to support HTTP but I'm unsure if that's possible due to server limitations. if you could do the same for HTTPS

**Comment by jaylagorio** [comment]
That sounds good to me! So I know for the future, how did you get to the "blocked insecure request" message?

**Comment by Rytiggy** [comment]
haha I plugged it into my dev console

**Comment by jaylagorio** [comment]
Gotcha. I'll see if I can shoehorn a certificate into my reverse proxy for that host. Thank you!

**Comment by jaylagorio** [comment]
So the good news is I was able to reroute traffic, implement Let's Encrypt (which has kind of been on my list of things to do for a while), and now everything works. I still think a non-default HTTP Is OK option would be helpful in the future.

Thanks for helping me figure this out!

**Comment by Rytiggy** [comment]
Thanks for this info I'll be looking in to it!
