### ISSUE TITLE
fitbit versa lite & xdrip+ and glance >> E404

### ISSUE THREAD

**Issue by jeroenvdooren** [Rytiggy/Glance#84]
please help : i have tried everything 
i am using samsung A8 latest updates included 
i am using xdrip apk juli 7 2019
and fitbit versa lite 
restarting phone, watch etc 

everything seems to sync properly between the smartwatch and the android phone 
however no CGM values

xdrip works fine with good values 

please help !!

**Comment by Rytiggy** [comment]
On your phone what do you see when you navigate to this url http://127.0.0.1:17580/sgv.json

**Comment by jeroenvdooren** [comment]
Thxs for the very fast replyAppreciatrdI getError connection refusedOp 20 juli 2019 om 13:35 schreef Ryan Mason <notifications@github.com>:  On your phone what do you see when you navigate to this url http://127.0.0.1:17580/sgv.json—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Rytiggy** [comment]
That sounds like you don't have the local xDrip Web Service  turned on: 
![image](https://user-images.githubusercontent.com/17414914/61578363-a24fe380-aac3-11e9-822b-8b8773420972.png)

**Comment by jeroenvdooren** [comment]
ThxsIt worksThxs again also for the speed !Op 20 juli 2019 om 13:55 schreef Ryan Mason <notifications@github.com>:  That sounds like you don't have the local xDrip Web Service turned on: —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Rytiggy** [comment]
glad we got it working!

**Comment by jeroenvdooren** [comment]
an i have a very happy daughter right now !
