### ISSUE TITLE
Allow background gradient to be user set in the settings UI.

### ISSUE THREAD

**Issue by gitanO0** [Rytiggy/Glance#9]
I have yet to have the new Versa delivered but was looking over this project and am super excited to give this a go.  
One minor feature request would be to allow the user to enter their own top and bottom background color values in the settings UI.  
Thanks much for this!!!

**Comment by Rytiggy** [comment]
Hey! 
I made a ticket for this, ill app some priority to this now that I know you want it, great suggestion!
https://github.com/Rytiggy/Glance/projects/1#card-8978546

**Comment by Rytiggy** [comment]
This has been added with 1.2.0 @gitanO0
