### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by katiecooke85** [Rytiggy/Glance#90]
Hi, my fit bit seems to have stopped automatically syncing so I constantly get the stale data message. I have to go in and resync in the fit bit app manually. The app is open in the background. Ivw uninstalled and reinstalled, restarted the fit bit etc. Any ideas? Worked perfectly till yesterday? I'm on andriod/miao miao/ versa. Thanks, it's driving me mad!!

**Comment by Rytiggy** [comment]
If you're using Dexcom as your data source their servers have been having trouble. It should be resolved by Dexcom soon.

**Comment by katiecooke85** [comment]
Hi, I'm not using dexcom. Xdrip and miao miao.

**Comment by Rytiggy** [comment]
Did anything change in your phone? Are you receiving constant readings in xDrip?

**Comment by katiecooke85** [comment]
No changes to my phone except it ran out of battery and switched off.

I'm getting readings to x drip yes.

Is it reliant on Wi-Fi?

Thanks, appreciate the help.

**Comment by katiecooke85** [comment]
Also when I tap on the refresh it no longer updates. Even if it's pulling
readings from xdrip (which works for about an hour before I get a constant
stale data message) it doesn't actually refresh it any more.

**Comment by katiecooke85** [comment]
It seems to be. If I change the clock face then change it back to glance,
it tends to work fine for a few hours, auto syncing but not updating if I
tap on the fitbit to refresh. Then it cuts out and updates in xdrip but
send nothing to the fitbit.

A few other non dexcom people seem to be having the same issue. Could it be
something fitbit have updated?

Thanks for your help!

**Comment by katiecooke85** [comment]
An example of someone else experiencing the same thing. Thanks.

**Comment by thomaas** [comment]
I had the same issue here.. Did a full factory reset and everything works fine since then. FitBit had an App Update but I dont know if this migth had affected the sync.

**Comment by katiecooke85** [comment]
I've just done this so fingers crossed. Thank you!

**Comment by katiecooke85** [comment]
This worked temporarily but it's now not auto syncing again.

**Comment by bboi61** [comment]
Samsung S4 mini (LineageOS 16) + Libre/MiaoMiao - xDrip+
It syncs for a few hours, then not at all. I can not find the mistake. Have already tried a lot. The Fitbit app also affects the synchronization of xDrip with MiaoMiao!

**Comment by Kolin** [comment]
I'm having the same problem with xDrip+ and MaioMiao on a Pixel 3.

**Comment by FredMK** [comment]
Some problem here, using with xDrip+. Temporary solution to open the alarm on the clock then go the the home screen. It will reload the watchface and everything working again for a few hours.

**Comment by Deezl117** [comment]
Having the same stale data issues most of the day like all other users. Mostly stale data with the occasional refresh/sync and updating when playing with Glance settings (changing settings, reverting, etc). Tried the alarm trick @FredMK used and that works for now. There was a recent Fitbit update that changed the app a bit. I'm wondering if this is the issue. For reference, I'm on an Android device using the Dexcom Share option.

**Comment by SonyaL13** [comment]
I am having the same issue with an Android device using the Dexcon share option. It used to work for a little while if I restarted my watch or played with the watch face settings but now it doesn't refresh.  Also, every once in awhile the time will show up very tiny on the left side of the screen over where the blood sugar reading is.

**Comment by jroth-haj** [comment]
I bypassed this by rolling back to older Fitbit app version.

**Comment by SonyaL13** [comment]
How do I do that?

**Comment by jroth-haj** [comment]
You can search at apkmirror.com.
I recommend Virus scanning of the downloaded file by uploading to virustotal.com

**Comment by Justine419** [comment]
I have the same issue, but it's not just Glance - I've used another CGM watchface and it's been doing the same thing. Likely a Fitbit problem? I'm using Xdrip as my data source for both.

**Comment by rherrera67** [comment]
Same is occurring to me, for at last a week. Perhaps even longer.  Set up Glance, works for a few minutes then I get the "Stale Data" message on the Fitbit.

Usually, I "just" go to the fitbit app (on my iphone), select the versa icon, select clock faces, select Glance, click on "Settings", scroll ALL. THE. WAY. DOWN... enable Advanced, scroll down even more, and click on "Resync" a few times.  And usually the glucose level updates on the watch.

Not a problem, right? WRONG... it is WAY to cumbersome and ridiculous to have to do that 30 times a day.

I have recently resorted to just carrying around the little Dexcom Receiver device I got when I first started with using Dexcom.  It is small and it NEVER loses connection.

So, if anyone has any ideas, on how to fix this, I would really appreciate it. Otherise I may just remove the app from my fitbit, as it is too annoying to continue to try to use it.

**Comment by dbi987** [comment]
After trying everything I could think of, at my next sensor change it also changed my transmitter which only had two weeks on it. Voila! It seems that the transmitted was not putting out consistent numbers. I am guessing I was getting similar inconsistencies with my Dexcom app, but noticed it more on my Fitbit as that’s what I check throughout the day.

Maybe try this if you haven’t already?

________________________________

**Comment by RTKurek** [comment]
Was this ever resolved? I'm still having this issue sporadically when syncing with xDrip.

**Comment by SonyaL13** [comment]
No, it never resolved.

 

 

Sincerely,

Sonya Lasserre

 

J&S Services, L.P.

P.O. Box 20942

Amarillo, TX 79114

Phone/Fax (806) 622-0990

js.serviceslp@suddenlink.net

**Comment by Rytiggy** [comment]
this isn't an issue with glance but an issue with Fitbit.
