### ISSUE TITLE
Allow to use custom URL for Nightscout

### ISSUE THREAD

**Issue by n0rb33r7** [Rytiggy/Glance#92]
Hi Ryan,

Can I ask you to allow to use custom URL for Nightscout? Right now, if I choose "Nightscout" as Data Source, I'm not able to use my own self-hosted instance as at "Nightscout Host Site" it adds either Heroku or Azure.

**Comment by jroth-haj** [comment]
You should User the custom url Endung with /pebble

n0rb33r7 <notifications@github.com> schrieb am Di., 3. Sep. 2019, 09:35:

**Comment by Rytiggy** [comment]
@n0rb33r7, this is already a feature in Glance just switch your data source to Custom like  @jroth-haj said :)
